name: Mac
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build_macos_intel:
    if: github.repository_owner == 'myridia'
    runs-on: macos-latest
    steps:
       - name: Dependencies
         run: |
          BOOTSTRAP_TAR="bootstrap-macos14.5-trunk-arm64-20251114.tar.gz"
          BOOTSTRAP_SHA="512a3c209fa0e83b4f614bc6ce11928c10b75cd0" 
          curl -O https://pkgsrc.smartos.org/packages/Darwin/bootstrap/${BOOTSTRAP_TAR}
          sudo tar -zxpf ${BOOTSTRAP_TAR} -C /
          
       - name: Checkout
         uses: actions/checkout@v4

       - name: Build
         run: |
           cmake -G Xcode -S . -B build -DCMAKE_INSTALL_PREFIX=/usr/local/nappgui -DCMAKE_POLICY_VERSION_MINIMUM=3.5 
           cmake --build build --config Release
           ls  build/Release/bin/
           ls build/Release/bin/hello_c_nappgui.app
           cd build/Release/bin/
           hdiutil create -volname "hello_c_nappgui" -srcfolder "hello_c_nappgui.app" -ov -format UDZO "hello_c_nappgui.dmg"
           #tar -czf hello_c_nappgui.app.tar.gz build/Release/bin/ ./hello_c_nappgui.app

       - name: Release
         uses: svenstaro/upload-release-action@v2
         with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/Release/bin/hello_c_nappgui.dmg'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true   
