name: Windows

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write env:
  issues: read
  packages: none

env:
  CURL_INCLUDE_DIR: C:\ProgramData\chocolatey\lib\curl\tools\curl-8.19.0_1-win64-mingw\include

jobs:
  Build:
    if: github.repository_owner == 'myridia'
    runs-on: windows-latest
    steps:
      - name: Dependencies
        run: |
          choco install curl tree -y
      - name: Check
        run: |
          $env:CURL_DIR
          tree C:\ProgramData\chocolatey\lib\curl
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
           cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
           cmake --build build       
           mv build/ftl_maker ftl_maker_mac 
        

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/ftl_maker.exe'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true  
        


 
     
